name: lms_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.3+9

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  firebase_messaging: ^15.0.0
  flutter_rating_bar: ^4.0.1
  pod_player: ^0.2.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  flutter_html: ^3.0.0-beta.2
  easy_localization: ^3.0.7
  hive_flutter: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  flutter_riverpod: ^2.5.1
  carousel_slider: ^4.2.1
  google_fonts: ^6.2.1
  line_icons: ^2.0.3
  feather_icons: ^1.2.0
  cached_network_image: ^3.3.1
  simple_animations: ^5.0.2
  font_awesome_flutter: ^10.7.0
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6+1
  in_app_purchase_platform_interface: ^1.4.0
  in_app_purchase_storekit: ^0.3.16
  flutter_web_browser: ^0.17.1
  quiver: ^3.2.1
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  firebase_storage: ^12.0.0
  material_dialogs: ^1.1.4
  path_provider: ^2.1.3
  app_settings: ^5.1.1
  loading_indicator: ^3.1.1
  smooth_page_indicator: ^1.1.0
  gap: ^3.0.1
  launch_review: ^3.0.1
  local_auth: ^2.2.0
  shimmer: ^3.0.0
  google_mobile_ads: ^5.1.0
  html_unescape: ^2.0.0
  share_plus: ^9.0.0
  firebase_analytics: ^11.0.0
  screen_protector: ^1.4.2
  
  
  firebase_crashlytics: ^4.0.0
  flutter_screenutil: ^5.9.3
  responsive_builder: ^0.7.0
  permission_handler: ^11.3.1
  equatable: ^2.0.5
  pull_to_refresh: ^2.0.0
  pinput: ^5.0.0
  flutter_bloc: ^8.1.6
  calendar_date_picker2: ^1.0.3
  flash: ^3.1.0
  flutter_easyloading: ^3.0.5
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  
  rounded_loading_button:
    git:
      url: https://github.com/scopendo/flutter_rounded_loading_button.git
      ref: master
  flutter_local_notifications: ^17.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.1


#flutter_launcher_icons:
 # android: "launcher_icon"
  #ios: true
  #image_path: "assets/icon/icon.png"
  #min_sdk_android: 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/animations/
   - assets/images/
   - assets/translations/
flutter_intl:
   enabled: true
   
flutter_launcher_icons:
  image_path_android: "assets/png/icon.png"
  image_path_ios: "assets/png/icon.png"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/png/icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/png/icon.png" # only available for Android 8.0 devices and above
  min_sdk_android: 24 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#8DDB90"
  android:
    background_color: "#8DDB90"
    image_path: "assets/png/icon.png"
  web:
    generate: true
    image_path: "assets/png/icon.png"
    background_color: "#8DDB90"
    theme_color: "#8DDB90"
  windows:
    generate: true
    image_path: "assets/png/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/png/icon.png"
        


    
