// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeG2Vn6UliEa8kzcvBvqagE1E9IsWK7oQ',
    appId: '1:29827819454:android:5f6cb94ad77b510dc33bef',
    messagingSenderId: '29827819454',
    projectId: 'payment-notification-61830',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq_-aTeHIQ73s0IZ9YUQzAN2jgPtmbPb4',
    appId: '1:29827819454:ios:6f227fd121f4e2dfc33bef',
    messagingSenderId: '29827819454',
    projectId: 'payment-notification-61830',
    iosBundleId: 'FFTCompany.Evchanger',
    storageBucket: 'payment-notification-61830.appspot.com',
  );
}
