// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIAMuapIP85deFBkBA8YLGchewjMOCEes',
    appId: '1:577388184102:android:68ccfa0dda807ee7abdce7',
    messagingSenderId: '577388184102',
    projectId: 'elearning-ca768',
    storageBucket: 'elearning-ca768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCitq3FDRIwfhlQIiunUS5_-pK-NAxeOWE',
    appId: '1:577388184102:ios:cfca5778f17c05edabdce7',
    messagingSenderId: '577388184102',
    projectId: 'elearning-ca768',
    storageBucket: 'elearning-ca768.appspot.com',
    androidClientId: '577388184102-em447obgr06mt1qphb8fe8qtg5sn7rpo.apps.googleusercontent.com',
    iosClientId: '577388184102-iumlma6tp7nogajc0lc4pbirrge6t6f8.apps.googleusercontent.com',
    iosBundleId: 'FFTCompany.elearninglms',
  );
}
